version: "3.6"
services:
  app:
    build:
      context: "./app"
      dockerfile: Dockerfile
    networks:
      - demo
    environment:
      APP_ENV: development
    volumes:
      - "./app:/app"
    ports:
      - "80:3000"
    command: sh -c "yarn && yarn dev"

networks:
  demo:
    name: demo_network
