import Head from "next/head"
import Image from "next/image"
import { useMemo, useState } from "react"
import styles from "../styles/Home.module.css"
import styled from "styled-components"

import { to1Kg, kgTo } from "../formula/weight"

import Weight from "components/weight"

const Radio = styled.input``

export default function Home() {
  const [value, setValue] = useState(null)
  const [input, setInput] = useState("")
  const result = useMemo(() => {
    const kgValue = to1Kg({ type: input, value })
    return kgTo({ type: input, value: kgValue })
  }, [value, input])
  return (
    <div className="h-screen dark:bg-slate-900 text-gray-200">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Weight />
    </div>
  )
}
